**Add compatibility tests for ZipStore mode in Xenium reader**
The sparrow.io.xenium() function is currently failing because of a mismatch between spatialdata-io v0.6.0 and zarr v2.18.7 :
		TypeError: ZipStore.__init__() got an unexpected keyword argument 'read_only'

The crash is caused by one API mismatch: spatialdata-io 0.6.0 calls zarr.storage.ZipStore(..., read_only=True) which is the newer Zarr 3-style API. But currently, we have installed zarr 2.18.7 in our venv which does not accept read_only.
As I didn't want to change package versions that would break a million other dependencies, I resolved the issue by changing the zarr.storage.Zipstore() function at runtime only at src\sparrow\io\_xenium.py
In addition also a test was added to check if the xenium reader can deal with passing the read_only parameter.